name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Push to Hugging Face Space
      run: |
        # Clone the Space repo
        git clone https://nabanita-dg:$HF_TOKEN@huggingface.co/spaces/nabanita-dg/util-mood-classifier https://github.com/nabanita-dg/util-mood-classifier/
        cp -r * space-repo/
        cd space-repo

        # Pull first to avoid conflicts
        git pull origin main --allow-unrelated-histories

        git add .
        git commit -m "Auto-deploy from GitHub Actions 🚀" || echo "Nothing to commit"
        git push
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
